spring.application.name=validador-fotos

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/validadorFotos
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=America/Bogota

app.security.jwt.secret=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
app.security.jwt.expiration-ms=3600000

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=3a9e5dfcbe5e5f
spring.mail.password=55d95f14d63bc3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=no-reply@validadorfotos.local
app.frontend.reset-url=http://localhost:4200/reset-password
